name: CI

on:
  push:
  pull_request:
  

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Shellcheck
        run: shellcheck bin/authswitch lib/*.sh install.sh uninstall.sh examples/*.sh tests/run.sh scripts/cleanup_examples.sh

      - name: Integration tests
        run: bash tests/run.sh
